# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Cancer Genomics"
description: "Open-Source Bioinformatics Research & Mutation Analysis"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/johnultimate/CancerGenomics" 

# Minimal Dark Mode Theme
theme: minima
minima:
  skin: dark  # This enables dark mode readability
  date_format: "%b %-d, %Y"

# Permalinks - Set up clean URLs for project pages
permalink: /:categories/:title/

# Navigation for easy access
header_pages:
  - mutation-analysis.md
  - research-paper.md
  - about.md

# Markdown settings for clean writing
markdown: kramdown
highlighter: rouge

# Exclude unnecessary files from site generation
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

# Include custom header files
include: ["_includes"]